//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCyTICVideos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtro
    {
        public int id_filtro { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan duracion { get; set; }
        public int videos { get; set; }
    
        public virtual Video Video { get; set; }
    }
}
