//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCyTICVideos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario1
    {
        public int id_usuario { get; set; }
        public string username { get; set; }
        public int rol { get; set; }
        public string password { get; set; }
    
        public virtual Rol Rol1 { get; set; }
    }
}
