//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCyTICVideos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Filtroes = new HashSet<Filtro>();
        }
    
        public int id_video { get; set; }
        public int casette { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan duracion { get; set; }
    
        public virtual Casette Casette1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filtro> Filtroes { get; set; }
    }
}
