USE [Videos]
GO

/****** Object:  Table [dbo].[Formato]    Script Date: 9/24/2020 20:14:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Formato](
	[id_formato] [int] IDENTITY(1,1) NOT NULL,
	[formato] [text] NOT NULL,
	[estado] [int] NOT NULL,
 CONSTRAINT [PK_Formato] PRIMARY KEY CLUSTERED 
(
	[id_formato] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


